name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - prd.*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prepare wrangler.toml
        run: |
          sed -i '/^\(bucket_name\).*$/s//\1 = "file"/' wrangler.toml
          sed -i '/^\(preview_bucket_name\).*$/s//\1 = "file"/' wrangler.toml
          sed -i '/^\(ITEMS_PER_PAGE\).*$/s//\1 = 100/' wrangler.toml
          sed -i '/^\(ALLOWED_ORIGINS\).*$/s//\1 = "${{ secrets.CF_DOMAIN }}"/' wrangler.toml
      - name: Publish
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
